### ISSUE TITLE
Pros and Cons comparison

### ISSUE THREAD

**Issue by NikitaIT** [florian-lefebvre/astro-env#3]
Hello, I greatly appreciate the excellent work you've been doing. I'm interested in learning more about this package.

Could you please explain how the approach adopted by this package is superior to the one used at https://env.t3.gg/docs/core? A brief comparison would be appreciated.

I believe this explanation could also benefit future users.

**Comment by florian-lefebvre** [comment]
Hi, thanks for reaching out! This package has a different scope for now than t3 env. t3 env uses zod to perform advanced validation and you gotta use a new `env` variable. However, `astro-env` does 2 simple things:
1. check if you have all your variables set
2. type `import.meta.env` through codegen

it really depends on what you're looking for. imo this package is more integrated with astro and provides a quite nice dx but if you need something more advanced, t3 env may be a better fit.

FYI this package led to an rfc to bring this feature to Astro itself! If you have any insight, we'd love your feedback! You can read more at https://github.com/withastro/roadmap/issues/837

**Comment by florian-lefebvre** [comment]
I'm closing as this package is now deprecated. Astro 4.10 now has `astro:env` in experimental: https://astro.build/blog/astro-4100/
